---
artifacts:
  type: zip
  files:
  - packaged-east-region.yaml
  - packaged-west-region.yaml
phases:
  build:
    commands:
    - sam build
  post_build:
    commands:
    - echo "********BUILD PHASE - CF PACKAGING**********"
    - sam package  --output-template-file packaged-east-region.yaml --s3-bucket $S3_US_EAST_1 --region us-east-1
    - sam package  --output-template-file packaged-west-region.yaml --s3-bucket $S3_US_WEST_1 --region us-west-1
    #- sam package --template-file template-east.yaml --output-template-file packaged-east-region.yaml --s3-bucket $S3_US_EAST_1 --region us-east-1
    #- sam package --template-file template-west.yaml --output-template-file packaged-west-region.yaml --s3-bucket $S3_US_WEST_1 --region us-west-1
  install:
    runtime-versions:
      java: corretto11
version: 0.2