version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AvailableToPromiseApi-Dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3maelql6z6vy"
s3_prefix = "AvailableToPromiseApi-Dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"Dev\""
