AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AvailableToPromise API
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
Parameters:
  StageName:
    Description: stage / alias name to be used in this deploy
    Type: String
    AllowedValues:
      - Prod
      - UAT
      - Dev
      - SBX
    Default: SBX
Conditions:
  CreatePRODResources: !Equals [!Ref StageName, Prod]
  CreateUATResources: !Equals [!Ref StageName, UAT]
  CreateDevResources: !Equals [!Ref StageName, Dev]
Mappings:
  EnvMap: 
    SBX: 
      DAXENDPOINT: daxs://dax-api-cluster-sbx.55wwgb.dax-clusters.us-east-2.amazonaws.com
      POLICYDAXRESOURCE: "arn:aws:dax:us-east-2:046651523196:cache/dax-api-cluster-sbx"
      POLICYDDBRESOURCE: ["arn:aws:dynamodb:us-east-2:046651523196:table/UPC_SKU_MAPPING"]
      SECURITYGROUPID: [sg-0464ca77356167d55]
      SUBNETID: [subnet-006dbc8ed3674054f,subnet-00c7d2404ff788540]
      FUNMEMORYSIZE: 5120
      UPCTABLE: UPC_SKU_MAPPING
      INVENTORYFUN: InventoryApi-SBX
      DDFUN: DeliveryDateApi-SBX
      GEOLOCATIONFUN: GeoLocationApi-SBX
    Dev: 
      DAXENDPOINT: daxs://dax-api-cluster-dev.1stt4v.dax-clusters.us-east-2.amazonaws.com
      POLICYDAXRESOURCE: "arn:aws:dax:us-east-2:476435662168:cache/dax-api-cluster-dev"
      POLICYDDBRESOURCE: ["arn:aws:dynamodb:us-east-2:476435662168:table/UPC_SKU_MAPPING"]
      SECURITYGROUPID: [sg-02ee49aabe83fbfd4]
      SUBNETID: [subnet-004162eb921739d5e,subnet-0f3f48ad97d5108e8]
      FUNMEMORYSIZE: 5120
      UPCTABLE: UPC_SKU_MAPPING
      INVENTORYFUN: InventoryApi-Dev
      DDFUN: DeliveryDateApi-Dev
      GEOLOCATIONFUN: GeoLocationApi-Dev
    UAT: 
      DAXENDPOINT: daxs://dax-api-cluster-uat.4o0d6x.dax-clusters.us-east-2.amazonaws.com #daxs://inventorytestcluster.yprieo.dax-clusters.us-west-1.amazonaws.com  
      POLICYDAXRESOURCE: "arn:aws:dax:us-east-2:545738172159:cache/dax-api-cluster-uat"
      POLICYDDBRESOURCE: ["arn:aws:dynamodb:us-east-2:545738172159:table/UPC_SKU_MAPPING"]
      SECURITYGROUPID: [sg-0492937f9338bde20]
      SUBNETID: [subnet-0ce921c9a0bfbf476,subnet-0c8129a992b9ab85c]
      FUNMEMORYSIZE: 5120
      UPCTABLE: UPC_SKU_MAPPING
      INVENTORYFUN: InventoryApi-UAT
      DDFUN: DeliveryDateApi-UAT
      GEOLOCATIONFUN: GeoLocationApi-UAT
    Prod: 
      DAXENDPOINT: daxs://dax-api-cluster-prod.0ll8yb.dax-clusters.us-east-2.amazonaws.com #daxs://inventorytestcluster.yprieo.dax-clusters.us-west-1.amazonaws.com  
      POLICYDAXRESOURCE: "arn:aws:dax:us-east-2:677067958011:cache/dax-api-cluster-prod"
      POLICYDDBRESOURCE: ["arn:aws:dynamodb:us-east-2:677067958011:table/UPC_SKU_MAPPING"]
      SECURITYGROUPID: [sg-022f2ff41edac9bd2]
      SUBNETID: [subnet-0a431b4df3413dd1d,subnet-0581e68ac82334442,subnet-0310474c88d5860f9]
      FUNMEMORYSIZE: 5120
      UPCTABLE: UPC_SKU_MAPPING 
      INVENTORYFUN: InventoryApi-Prod
      DDFUN: DeliveryDateApi-Prod
      GEOLOCATIONFUN: GeoLocationApi-Prod 
Resources:
  AvailableToPromiseFunctionLogGroup:
    Type: "AWS::Logs::LogGroup"
    DependsOn: "AvailableToPromiseFunction"
    Properties: 
      RetentionInDays: 30
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref AvailableToPromiseFunction]]
  AvailableToPromiseFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Join [ "-", [AvailableToPromiseApi, !Ref StageName] ]  #!Join [ ":", [ a, b, c ] ]
      Description: AvailableToPromise API.
      CodeUri: 
      Handler: com.conns.lambda.api.atp.AvailableToPromiseHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      Policies:
      - Statement:
        - Sid: DAXLambdaAccessPolicy
          Effect: Allow
          Action:
          - dax:*
          Resource: !FindInMap [EnvMap, !Ref StageName, POLICYDAXRESOURCE] # !If [CreateEastResources, !FindInMap [EastRegEnvMap, !Ref StageName, POLICYDAXRESOURCE], !FindInMap [WestRegEnvMap, !Ref StageName, POLICYDAXRESOURCE]]
        - Sid: DYDBAccessPolicy
          Effect: Allow
          Action:
          - dynamodb:*
          Resource: !FindInMap [EnvMap, !Ref StageName, POLICYDDBRESOURCE] #!If [CreateEastResources, !FindInMap [EastRegEnvMap, !Ref StageName, POLICYDDBRESOURCE], !FindInMap [WestRegEnvMap, !Ref StageName, POLICYDDBRESOURCE]] 
      - LambdaInvokePolicy:
          FunctionName: !FindInMap
                          - EnvMap
                          - !Ref StageName
                          - INVENTORYFUN
      - LambdaInvokePolicy:
          FunctionName: !FindInMap
                          - EnvMap
                          - !Ref StageName
                          - DDFUN
      - LambdaInvokePolicy:
          FunctionName: !FindInMap
                          - EnvMap
                          - !Ref StageName
                          - GEOLOCATIONFUN
      VpcConfig:
        SecurityGroupIds: !FindInMap [EnvMap, !Ref StageName, SECURITYGROUPID] 
        SubnetIds:  !FindInMap [EnvMap, !Ref StageName, SUBNETID]
      MemorySize: !FindInMap
            - EnvMap
            - !Ref StageName
            - FUNMEMORYSIZE
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          VERSION: 1.0
          RESTART: 1.0  # Change this value at runtime to force restart
          LOG_LEVEL: DEBUG
          DISTANCETHRESHOLD: 75
          CLEARANCESTORES: 290,266
          ADJUSTEDSTART: 10-31-2023 11:45 PM America/Chicago
          ADJUSTEDEND: 10-31-2023 11:50 PM America/Chicago
          ADJUSTEDDAYS: 1
          INVENTORYFUN: !FindInMap
            - EnvMap
            - !Ref StageName
            - INVENTORYFUN
          DDFUN: !FindInMap
            - EnvMap
            - !Ref StageName
            - DDFUN
          GEOLOCATIONFUN: !FindInMap
            - EnvMap
            - !Ref StageName
            - GEOLOCATIONFUN
          UPCTABLE: !FindInMap
            - EnvMap
            - !Ref StageName
            - UPCTABLE
          DAXENDPOINT:  !FindInMap [EnvMap, !Ref StageName, DAXENDPOINT] 